name: PR Linters and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-integration-test:
    name: linter and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install NPM packages
        run: npm install

      - name: Run tests
        run: npm run test -- --coverage

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        start: npm start
          wait-on: 'http://localhost:3000'
          browser: chrome
          headless: true
