name: PR Linters and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-integration-test:
    name: linter and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install NPM packages
        run: npm install
      - name: Run tests
        run: npm run test -- --coverage

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - name: Run CRA Build
        run: yarn build
      - name: Save Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build
  e2e_tests:
    runs-on: ubuntu-latest
    needs: install
    container: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Cypress artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
